"use strict";
exports.__esModule = true;
var Product_1 = require("./Product");
var ProductService_1 = require("./ProductService");
var _productService = new ProductService_1["default"]();
var result;
result = _productService.getById(3);
console.log(result);
//result = _productService.getProducts();
//console.log(result);
var p = new Product_1["default"]();
p.id = 2;
p.name = "IPhone 13 PRO";
p.price = 30000;
p.category = "Telefon";
_productService.saveProduct(p);
console.log("-----------------------------------------------");
result = _productService.getProducts();
console.log(result);
